# Allows you to define the applicable items
Applicable Item Keywords:
  night_vision:
    - "helmet"
    - "pumpkin"

# Restricts certain items via keywords.
Restricted Item Keywords:
  night_vision:
    - "diamond"
    - "iron"
