name: PotionMarker
version: 1.0-SNAPSHOT
main: net.dohaw.potionmarker.PotionMarkerPlugin
api-version: 1.13

commands:
  potionmarker:
    aliases:
      - pma
      - potionm
      - pmark
      - pmarker

permissions:
  potionmarker.mark:
    default: op
    description: Allows players to mark their items
  potionmarker.reload:
    default: op
    description: Permission to reload the plugin
